package by.training.karpilovich.lowcost.command;

public enum Attribute {
	
	USER, ROLE, PAGE_FROM, IS_LOGIN, LOCALE, ERROR_MESSAGE, PAGE_TO, FLIGHTS, CITY, CITIES, PLANES, FLIGHT, BOUND_FROM,
	MAX_BOUND_VALUE, DATE_COEFFICIENT, PLACE_COEFFICIENT;

}