package by.training.karpilovich.lowcost.command;

public enum CommandType {
	SIGN_IN, SIGN_OUT, SIGN_UP, REMOVE, ADD_CITY, SHOW_ALL_CITIES, REDIRECT, SEARCH_FLIGHT, CHANGE_LANGUAGE,
	DELETE_CITY, REDIRECT_TO_UPDATE_CITY_PAGE, UPDATE_CITY, REDIRECT_TO_CREATE_FLIGTH_PAGE, CREATE_FLIGHT,
	REDIRECT_TO_ADD_LUGGAGE_COEFFICIENT_PAGE, REDIRECT_TO_ADD_PLACE_COEFFICIENT_PAGE, REDIRECT_TO_ADD_DATE_COEFFICIENT_PAGE,
	ADD_LUGGAGE_COEFFICIENT, 
	ADD_PLACE_COEFFICIENT, ADD_DATE_COEFFICIENT, ADD_FLIGHT, REDIRECT_TO_FLIGHT_PREVIEW_PAGE,
	SHOW_ALL_FLIGHTS, REMOVE_LUGGAGE_COEFFICIENT, REMOVE_DATE_COEFFICIENT, REMOVE_PLACE_COEFFICIENT;
}